# Generated by Django 5.1.2 on 2025-08-01 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_enrolled_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='enrolled_video_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
